#pragma once

#define ENABLE_COMPILE_KEYCODE

#define ONESHOT_TAP_TOGGLE 5
#define ONESHOT_TIMEOUT 600000

#define COMBO_STRICT_TIMER
#define COMBO_ONLY_FROM_LAYER 0
#define COMBO_TERM 75

#define ENABLE_RGB_MATRIX_STARLIGHT_DUAL_SAT
#define ENABLE_RGB_MATRIX_SOLID_COLOR
#define RGB_MATRIX_SLEEP
#define RGB_MATRIX_TIMEOUT 900000
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_STARLIGHT_DUAL_SAT
#define RGB_MATRIX_DEFAULT_HUE 127
#define RGB_MATRIX_DEFAULT_SAT 220
#define RGB_MATRIX_DEFAULT_VAL RGB_MATRIX_MAXIMUM_BRIGHTNESS
#define RGB_MATRIX_DEFAULT_SPD 127
