#pragma once

#define TAPPING_TERM 250

#define COMBO_STRICT_TIMER
#define COMBO_ONLY_FROM_LAYER 0
#define COMBO_TERM 75

#define SPLIT_LAYER_STATE_ENABLE
#define SPLIT_MODS_ENABLE
#define SPLIT_LED_STATE_ENABLE

#define ENABLE_RGB_MATRIX_SOLID_COLOR
#define ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
#define X_LAYER_EFFECT_DEFAULT 0x000000
#define RGB_MATRIX_HUE_STEP 4
#define RGB_MATRIX_SAT_STEP 8
#define RGB_MATRIX_VAL_STEP 8
#define RGB_MATRIX_SLEEP
#define RGB_MATRIX_TIMEOUT 900000
