#pragma once

// Hold Tap
#define IGNORE_MOD_TAP_INTERRUPT
#define TAPPING_TERM 250
#define HOLD_ON_OTHER_KEY_PRESS

// Combos
#define COMBO_STRICT_TIMER
#define COMBO_ONLY_FROM_LAYER 0
#define COMBO_SHOULD_TRIGGER
#define COMBO_TERM 75

#define NO_DILEMMA_KEYCODES
#define ENCODER_DIRECTION_FLIP
#define CIRQUE_PINNACLE_TAP_ENABLE
#define DILEMMA_MINIMUM_DEFAULT_DPI 300
#define CIRQUE_PINNACLE_TAPPING_TERM 300
#define CIRQUE_PINNACLE_TOUCH_DEBOUNCE 100000
#define CIRQUE_PINNACLE_ATTENUATION EXTREG__TRACK_ADCCONFIG__ADC_ATTENUATE_4X

// RGB
#define ENABLE_RGB_MATRIX_SOLID_COLOR
#define ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
#define RGB_MATRIX_VAL_STEP 8
#define X_LAYER_EFFECT_UNDERGLOW 0x0b0bff
#define RGB_MATRIX_LED_PROCESS_LIMIT 10
#define RGB_MATRIX_LED_FLUSH_LIMIT 33

#define SPLIT_LAYER_STATE_ENABLE
#define SPLIT_MODS_ENABLE

